### ISSUE TITLE
Permission/access credentials to download relations

### ISSUE THREAD

**Issue by jubosgil** [Wluper/Retrograph#6] opened 2020-12-17 08:23 UTC
Hi, my colleagues and I at University of Zaragoza attempted to follow the documentation to try your approach. However, we are running into permission issues, as we do not have the necessary credentials to access the AWS bucket and download the relations. Any ideas on how to get around this problem to continue with the next steps in the documentation? Thanks very much!

**Comment by anlausch** [comment] 2021-02-03 10:55
Hi jubosgil,
thanks for pointing out the issue! We hope to fix this within this weak. In the meantime, you can find the relations here: 
https://drive.google.com/drive/folders/1FiTcdDXujmQwds4q3Mwpb4X86hZFpGV5?usp=sharing
Please also notice that I'll update the conversation code in a couple of hours and that you have the newest version. Thanks.
Cheers
Anne

**Comment by ai-nikolai** [comment] 2021-02-19 11:42
Hi, 

Also a thank you from my side for submitting and finding this issue. 

Please, let me know if this PR solves your issue:
https://github.com/Wluper/Retrograph/pull/10
(already merged into master)

**Comment by ai-nikolai** [comment] 2021-02-19 18:16
If the issue still persists, here from Issue 9: https://github.com/Wluper/Retrograph/issues/9

---------------------------------------------
We understand the bug now.

The problem is basically in the package awscli requires its own configuration (which we had by default on our machines). We will try and push a fix over the next couple of weeks (when awscli is not configured on a machine). However, in the mean-time you can fix it by configuring aws directly first!

Here our version numbers for reference:

wluper-system$ aws --version
aws-cli/1.19.8 Python/3.6.5 Darwin/19.6.0 botocore/1.20.8
Steps To solve the problem:

Install awscli (version 1), Run: pip3 install awscli<1.19.8 --upgrade --user
Run the command: aws configure (choose default region eu-west-2)
Try running the whole thing again.

**Comment by ai-nikolai** [comment] 2021-02-22 21:12
After working actively on a similar issue: https://github.com/Wluper/Retrograph/issues/9

This should be solved now, please see the thread there to see the results.

**Closed** 2021-10-01 14:43 UTC
